site_name: Sustaina API Specs
site_description: Position template API contract and ERD
site_url: https://tan3warut4.github.io/sustaina-api-specs
nav:
  - Overview: index.md
  - API: openapi.md
  - ER Diagram: position-template-erd.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.tasklist
  - toc:
      permalink: true
  - tables
plugins:
  - search
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
extra_css:
  - css/extra.css
